add model training actions

diff --git a/.github/workflows/mlops-pipeline.yaml b/.github/workflows/mlops-pipeline.yaml
--- a/.github/workflows/mlops-pipeline.yaml
+++ b/.github/workflows/mlops-pipeline.yaml
@@ -50,71 +50,71 @@ jobs:
         name: preprocessor
         path: models/trained/preprocessor.pkl
         
-  # model-training:
-  #   needs: data-processing
-  #   runs-on: ubuntu-latest
+  model-training:
+    needs: data-processing
+    runs-on: ubuntu-latest
     
-  #   steps:
-  #   - name: Checkout code
-  #     uses: actions/checkout@v2
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v2
       
-  #   - name: Set up Python
-  #     uses: actions/setup-python@v2
-  #     with:
-  #       python-version: '3.11.9'
+    - name: Set up Python
+      uses: actions/setup-python@v2
+      with:
+        python-version: '3.11.9'
         
-  #   - name: Install dependencies
-  #     run: |
-  #       python -m pip install --upgrade pip
-  #       pip install -r requirements.txt
+    - name: Install dependencies
+      run: |
+        python -m pip install --upgrade pip
+        pip install -r requirements.txt
         
-  #   - name: Download processed data
-  #     uses: actions/download-artifact@v4
-  #     with:
-  #       name: processed-data
-  #       path: data/processed/
+    - name: Download processed data
+      uses: actions/download-artifact@v4
+      with:
+        name: processed-data
+        path: data/processed/
         
-  #   # - name: Set up MLflow
-  #   #   run: |
-  #   #     docker pull ghcr.io/mlflow/mlflow:latest
-  #   #     docker run -d -p 5000:5000 \
-  #   #     --name mlflow-server ghcr.io/mlflow/mlflow:latest mlflow server \
-  #   #     --host 0.0.0.0 \
-  #   #     --backend-store-uri sqlite:///mlflow.db
+    # - name: Set up MLflow
+    #   run: |
+    #     docker pull ghcr.io/mlflow/mlflow:latest
+    #     docker run -d -p 5000:5000 \
+    #     --name mlflow-server ghcr.io/mlflow/mlflow:latest mlflow server \
+    #     --host 0.0.0.0 \
+    #     --backend-store-uri sqlite:///mlflow.db
     
-  #   - name: Set up MLflow using Docker Compose
-  #     run: |
-  #       docker compose -f deployment/mlflow/docker-compose.yaml up -d
+    - name: Set up MLflow using Docker Compose
+      run: |
+        docker compose -f deployment/mlflow/docker-compose.yaml up -d
         
-  #   - name: Wait for MLflow to start
-  #     run: |
-  #       for i in {1..10}; do
-  #         curl -f http://localhost:5555/health || sleep 5;
-  #       done
+    - name: Wait for MLflow to start
+      run: |
+        for i in {1..10}; do
+          curl -f http://localhost:5555/health || sleep 5;
+        done
         
-  #   - name: Train model
-  #     run: |
-  #       mkdir -p models
-  #       python src/models/train_model.py \
-  #       --config configs/model_config.yaml \
-  #       --data data/processed/featured_house_data.csv \
-  #       --models-dir models \
-  #       --mlflow-tracking-uri http://localhost:5555
+    - name: Train model
+      run: |
+        mkdir -p models
+        python src/models/train_model.py \
+        --config configs/model_config.yaml \
+        --data data/processed/featured_house_data.csv \
+        --models-dir models \
+        --mlflow-tracking-uri http://localhost:5555
         
-  #   - name: Upload trained model
-  #     uses: actions/upload-artifact@v4
-  #     with:
-  #       name: trained-model
-  #       path: models/
+    - name: Upload trained model
+      uses: actions/upload-artifact@v4
+      with:
+        name: trained-model
+        path: models/
         
-  #   # - name: Clean up MLflow
-  #   #   run: |
-  #   #     docker stop mlflow-server || true
-  #   #     docker rm mlflow-server || true
+    # - name: Clean up MLflow
+    #   run: |
+    #     docker stop mlflow-server || true
+    #     docker rm mlflow-server || true
     
-  #   - name: Clean up MLflow using Docker Compose
-  #     run: |
-  #       docker compose -f deployment/mlflow/docker-compose.yaml down -v || true
+    - name: Clean up MLflow using Docker Compose
+      run: |
+        docker compose -f deployment/mlflow/docker-compose.yaml down -v || true
         
   # build-and-publish:
     # needs: model-training
